name: CI asdf Plugin

on:
  push:
  pull_request:

jobs:
  asdf:
    name: "asdf plugin build"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-repos-sync: [0.0.1]
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "go-repos-sync --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
